name: openaimobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

scripts:
  build_runner_script: "flutter pub run build_runner build --delete-conflicting-outputs"

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  pull_down_button: ^0.9.3
  bottom_sheet: ^3.1.2
  
  #Data
  provider: ^6.0.5
  path_provider: ^2.0.15
  hive: ^2.2.3
  dio: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  very_good_analysis: ^4.0.0+1
  hive_generator: ^2.0.0
  flutter_dotenv: ^5.1.0

flutter:

  uses-material-design: true

  assets:
      - .env
      - assets/
      - assets/avatars/

